### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Rogenar** [terrarium-earth/Botarium#16]
version botarium-fabric-1.19.3-2.0.4 causes the mod ad_astra-fabric-1.19.3-1.13.1.jar to crash when running the mod

**Comment by Zuiron** [comment]
yeah same.

`Mapping target name conflicts detected:
  METHODs earth/terrarium/botarium/common/fluid/impl/SimpleFluidContainer/[clear, net/minecraft/class_3829/method_5448]()V -> clear
There were unfixable conflicts.
[16:04:06] [main/ERROR] (FabricLoader) Failed to remap mods!
 net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Unfixable conflicts
	at net.fabricmc.loader.impl.discovery.RuntimeModRemapper.remap(RuntimeModRemapper.java:174) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:256) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[?:?]
Caused by: java.lang.RuntimeException: Unfixable conflicts
	at net.fabricmc.tinyremapper.TinyRemapper.handleConflicts(TinyRemapper.java:867) ~[tiny-remapper-0.8.2.jar:0.8.2]
	at net.fabricmc.tinyremapper.TinyRemapper.propagate(TinyRemapper.java:767) ~[tiny-remapper-0.8.2.jar:0.8.2]
	at net.fabricmc.tinyremapper.TinyRemapper.mrjRefresh(TinyRemapper.java:1046) ~[tiny-remapper-0.8.2.jar:0.8.2]
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:898) ~[tiny-remapper-0.8.2.jar:0.8.2]
	at net.fabricmc.loader.impl.discovery.RuntimeModRemapper.remap(RuntimeModRemapper.java:120) ~[fabric-loader-0.14.14.jar:?]
	... 6 more`
